

colors = ['primary_paletteKeyColorColor', 'secondary_paletteKeyColorColor', 'tertiary_paletteKeyColorColor',
 'neutral_paletteKeyColorColor', 'neutral_variant_paletteKeyColorColor', 'primaryFixedColor', 'primaryFixedDimColor',
 'onPrimaryFixedColor', 'onPrimaryFixedVariantColor', 'secondaryFixedColor', 'secondaryFixedDimColor',
 'onSecondaryFixedColor', 'onSecondaryFixedVariantColor', 'tertiaryFixedColor', 'tertiaryFixedDimColor',
 'onTertiaryFixedColor', 'onTertiaryFixedVariantColor', 'material_style', 'primary_hue', 'accent_palette', 'accent_hue',
 '__module__', 'primary_palette', 'dynamic_color_quality', 'dynamic_color', 'dynamic_scheme_name',
 'dynamic_scheme_contrast', 'path_to_wallpaper', 'theme_style_switch_animation',
 'theme_style_switch_animation_duration', 'theme_style', '_get_theme_style', '_get_disabled_hint_text_color',
 'disabled_hint_text_color', '_determine_device_orientation', 'device_orientation', 'font_styles', 'on_colors',
 '_size_current_wallpaper', '_dark_mode', '__init__', 'set_colors', 'update_theme_colors', 'on_dynamic_scheme_name',
 'on_dynamic_scheme_contrast', 'on_path_to_wallpaper', 'switch_theme', 'sync_theme_styles', '_set_application_scheme',
 '_set_color_names', '_set_palette_color', '__dict__', '__doc__', '__new__', 'register_event_type',
 'unregister_event_types', 'unregister_event_type', 'is_event_type', 'bind', 'unbind', 'fbind', 'funbind', 'unbind_uid',
 'get_property_observers', 'events', 'dispatch', 'dispatch_generic', 'dispatch_children',
 '_EventDispatcher__proxy_setter', '_EventDispatcher__proxy_getter', 'setter', 'getter', 'property', 'create_property',
 'apply_property', 'proxy_ref', '__self__', '_kwargs_applied_init', '_proxy_ref', '__pyx_vtable__', '__reduce__',
 '__setstate__', 'properties', 'uid', '__repr__', '__hash__', '__str__', '__getattribute__', '__setattr__',
 '__delattr__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__reduce_ex__', '__subclasshook__',
 '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__', 'primaryColor', 'primaryContainerColor',
 'onPrimaryColor', 'onPrimaryContainerColor', 'secondaryColor', 'secondaryContainerColor', 'onSecondaryColor',
 'onSecondaryContainerColor', 'tertiaryColor', 'tertiaryContainerColor', 'onTertiaryColor', 'onTertiaryContainerColor',
 'surfaceColor', 'surfaceDimColor', 'surfaceBrightColor', 'surfaceContainerLowestColor', 'surfaceContainerLowColor',
 'surfaceContainerColor', 'surfaceContainerHighColor', 'surfaceContainerHighestColor', 'surfaceVariantColor',
 'surfaceTintColor', 'onSurfaceColor', 'onSurfaceLightColor', 'onSurfaceVariantColor', 'inverseSurfaceColor',
 'inverseOnSurfaceColor', 'inversePrimaryColor', 'backgroundColor', 'onBackgroundColor', 'errorColor',
 'errorContainerColor', 'onErrorColor', 'onErrorContainerColor', 'outlineColor', 'outlineVariantColor', 'shadowColor',
 'scrimColor', 'disabledTextColor', 'transparentColor', 'rippleColor', '__weakref__']
